#!/bin/sh
#deploy="false"
deploy="true"

image=premkalyan
version=1.0-SNAPSHOT
latest=true

#OPTIONS="--no-cache --force-rm"
#OPTIONS="--no-cache"
#OPTIONS="--force-rm"
OPTIONS=""

docker build ${OPTIONS} -t jarfile/${image}:1.0-SNAPSHOT .
if [ "$?" -eq 0 ] && [ ${deploy} == "true" ]; then
    docker push jarfile/${image}:1.0-SNAPSHOT
    if [ "$latest" == "true" ]; then
        docker tag jarfile/${image}:1.0-SNAPSHOT jarfile/${image}:latest
        docker push jarfile/${image}:latest
    fi
fi